
services:
    webapp:
        image: ysof_admin
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: ysof_admin_${NODE_ENV}
        ports:
            - "3000:80"