/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as auth500Import } from './routes/(auth)/500'

// Create Virtual Routes

const AuthenticatedIndexLazyImport = createFileRoute('/_authenticated/')()
const AuthenticatedTaiLieuLazyImport = createFileRoute(
  '/_authenticated/tai-lieu',
)()
const AuthenticatedTaiKhoanLazyImport = createFileRoute(
  '/_authenticated/tai-khoan',
)()
const AuthenticatedQuanLyLoiTacVuLazyImport = createFileRoute(
  '/_authenticated/quan-ly-loi-tac-vu',
)()
const AuthenticatedNhatKyChinhSuaLazyImport = createFileRoute(
  '/_authenticated/nhat-ky-chinh-sua',
)()
const AuthenticatedMuaLazyImport = createFileRoute('/_authenticated/mua')()
const AuthenticatedGiangVienLazyImport = createFileRoute(
  '/_authenticated/giang-vien',
)()
const AuthenticatedCongViecChungLazyImport = createFileRoute(
  '/_authenticated/cong-viec-chung',
)()
const AuthenticatedBanToChucLazyImport = createFileRoute(
  '/_authenticated/ban-to-chuc',
)()
const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignInLazyImport = createFileRoute('/(auth)/sign-in')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedLuongGiaQuanLyFormLazyImport = createFileRoute(
  '/_authenticated/luong-gia/quan-ly-form',
)()
const AuthenticatedLuongGiaKetQuaLazyImport = createFileRoute(
  '/_authenticated/luong-gia/ket-qua',
)()
const AuthenticatedHocVienDanhSachHocVienLazyImport = createFileRoute(
  '/_authenticated/hoc-vien/danh-sach-hoc-vien',
)()
const AuthenticatedDangKyMonQuanLyFormLazyImport = createFileRoute(
  '/_authenticated/dang-ky-mon/quan-ly-form',
)()
const AuthenticatedDangKyMonKetQuaDangKyLazyImport = createFileRoute(
  '/_authenticated/dang-ky-mon/ket-qua-dang-ky',
)()
const AuthenticatedChuDeNghiPhepLazyImport = createFileRoute(
  '/_authenticated/chu-de/nghi-phep',
)()
const AuthenticatedChuDeGuiEmailLazyImport = createFileRoute(
  '/_authenticated/chu-de/gui-email',
)()
const AuthenticatedChuDeDanhSachChuDeLazyImport = createFileRoute(
  '/_authenticated/chu-de/danh-sach-chu-de',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexLazyRoute = AuthenticatedIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)

const AuthenticatedTaiLieuLazyRoute = AuthenticatedTaiLieuLazyImport.update({
  id: '/tai-lieu',
  path: '/tai-lieu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/tai-lieu.lazy').then((d) => d.Route),
)

const AuthenticatedTaiKhoanLazyRoute = AuthenticatedTaiKhoanLazyImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/tai-khoan.lazy').then((d) => d.Route),
)

const AuthenticatedQuanLyLoiTacVuLazyRoute =
  AuthenticatedQuanLyLoiTacVuLazyImport.update({
    id: '/quan-ly-loi-tac-vu',
    path: '/quan-ly-loi-tac-vu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/quan-ly-loi-tac-vu.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedNhatKyChinhSuaLazyRoute =
  AuthenticatedNhatKyChinhSuaLazyImport.update({
    id: '/nhat-ky-chinh-sua',
    path: '/nhat-ky-chinh-sua',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/nhat-ky-chinh-sua.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedMuaLazyRoute = AuthenticatedMuaLazyImport.update({
  id: '/mua',
  path: '/mua',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/mua.lazy').then((d) => d.Route),
)

const AuthenticatedGiangVienLazyRoute = AuthenticatedGiangVienLazyImport.update(
  {
    id: '/giang-vien',
    path: '/giang-vien',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/giang-vien.lazy').then((d) => d.Route),
)

const AuthenticatedCongViecChungLazyRoute =
  AuthenticatedCongViecChungLazyImport.update({
    id: '/cong-viec-chung',
    path: '/cong-viec-chung',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/cong-viec-chung.lazy').then((d) => d.Route),
  )

const AuthenticatedBanToChucLazyRoute = AuthenticatedBanToChucLazyImport.update(
  {
    id: '/ban-to-chuc',
    path: '/ban-to-chuc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/ban-to-chuc.lazy').then((d) => d.Route),
)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignInLazyRoute = authSignInLazyImport
  .update({
    id: '/(auth)/sign-in',
    path: '/sign-in',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedLuongGiaQuanLyFormLazyRoute =
  AuthenticatedLuongGiaQuanLyFormLazyImport.update({
    id: '/luong-gia/quan-ly-form',
    path: '/luong-gia/quan-ly-form',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/luong-gia/quan-ly-form.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedLuongGiaKetQuaLazyRoute =
  AuthenticatedLuongGiaKetQuaLazyImport.update({
    id: '/luong-gia/ket-qua',
    path: '/luong-gia/ket-qua',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/luong-gia/ket-qua.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedHocVienDanhSachHocVienLazyRoute =
  AuthenticatedHocVienDanhSachHocVienLazyImport.update({
    id: '/hoc-vien/danh-sach-hoc-vien',
    path: '/hoc-vien/danh-sach-hoc-vien',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/hoc-vien/danh-sach-hoc-vien.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDangKyMonQuanLyFormLazyRoute =
  AuthenticatedDangKyMonQuanLyFormLazyImport.update({
    id: '/dang-ky-mon/quan-ly-form',
    path: '/dang-ky-mon/quan-ly-form',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dang-ky-mon/quan-ly-form.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDangKyMonKetQuaDangKyLazyRoute =
  AuthenticatedDangKyMonKetQuaDangKyLazyImport.update({
    id: '/dang-ky-mon/ket-qua-dang-ky',
    path: '/dang-ky-mon/ket-qua-dang-ky',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dang-ky-mon/ket-qua-dang-ky.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedChuDeNghiPhepLazyRoute =
  AuthenticatedChuDeNghiPhepLazyImport.update({
    id: '/chu-de/nghi-phep',
    path: '/chu-de/nghi-phep',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/chu-de/nghi-phep.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedChuDeGuiEmailLazyRoute =
  AuthenticatedChuDeGuiEmailLazyImport.update({
    id: '/chu-de/gui-email',
    path: '/chu-de/gui-email',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/chu-de/gui-email.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedChuDeDanhSachChuDeLazyRoute =
  AuthenticatedChuDeDanhSachChuDeLazyImport.update({
    id: '/chu-de/danh-sach-chu-de',
    path: '/chu-de/danh-sach-chu-de',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/chu-de/danh-sach-chu-de.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/ban-to-chuc': {
      id: '/_authenticated/ban-to-chuc'
      path: '/ban-to-chuc'
      fullPath: '/ban-to-chuc'
      preLoaderRoute: typeof AuthenticatedBanToChucLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/cong-viec-chung': {
      id: '/_authenticated/cong-viec-chung'
      path: '/cong-viec-chung'
      fullPath: '/cong-viec-chung'
      preLoaderRoute: typeof AuthenticatedCongViecChungLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/giang-vien': {
      id: '/_authenticated/giang-vien'
      path: '/giang-vien'
      fullPath: '/giang-vien'
      preLoaderRoute: typeof AuthenticatedGiangVienLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/mua': {
      id: '/_authenticated/mua'
      path: '/mua'
      fullPath: '/mua'
      preLoaderRoute: typeof AuthenticatedMuaLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/nhat-ky-chinh-sua': {
      id: '/_authenticated/nhat-ky-chinh-sua'
      path: '/nhat-ky-chinh-sua'
      fullPath: '/nhat-ky-chinh-sua'
      preLoaderRoute: typeof AuthenticatedNhatKyChinhSuaLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/quan-ly-loi-tac-vu': {
      id: '/_authenticated/quan-ly-loi-tac-vu'
      path: '/quan-ly-loi-tac-vu'
      fullPath: '/quan-ly-loi-tac-vu'
      preLoaderRoute: typeof AuthenticatedQuanLyLoiTacVuLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/tai-khoan': {
      id: '/_authenticated/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof AuthenticatedTaiKhoanLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/tai-lieu': {
      id: '/_authenticated/tai-lieu'
      path: '/tai-lieu'
      fullPath: '/tai-lieu'
      preLoaderRoute: typeof AuthenticatedTaiLieuLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chu-de/danh-sach-chu-de': {
      id: '/_authenticated/chu-de/danh-sach-chu-de'
      path: '/chu-de/danh-sach-chu-de'
      fullPath: '/chu-de/danh-sach-chu-de'
      preLoaderRoute: typeof AuthenticatedChuDeDanhSachChuDeLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chu-de/gui-email': {
      id: '/_authenticated/chu-de/gui-email'
      path: '/chu-de/gui-email'
      fullPath: '/chu-de/gui-email'
      preLoaderRoute: typeof AuthenticatedChuDeGuiEmailLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chu-de/nghi-phep': {
      id: '/_authenticated/chu-de/nghi-phep'
      path: '/chu-de/nghi-phep'
      fullPath: '/chu-de/nghi-phep'
      preLoaderRoute: typeof AuthenticatedChuDeNghiPhepLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/dang-ky-mon/ket-qua-dang-ky': {
      id: '/_authenticated/dang-ky-mon/ket-qua-dang-ky'
      path: '/dang-ky-mon/ket-qua-dang-ky'
      fullPath: '/dang-ky-mon/ket-qua-dang-ky'
      preLoaderRoute: typeof AuthenticatedDangKyMonKetQuaDangKyLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/dang-ky-mon/quan-ly-form': {
      id: '/_authenticated/dang-ky-mon/quan-ly-form'
      path: '/dang-ky-mon/quan-ly-form'
      fullPath: '/dang-ky-mon/quan-ly-form'
      preLoaderRoute: typeof AuthenticatedDangKyMonQuanLyFormLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/hoc-vien/danh-sach-hoc-vien': {
      id: '/_authenticated/hoc-vien/danh-sach-hoc-vien'
      path: '/hoc-vien/danh-sach-hoc-vien'
      fullPath: '/hoc-vien/danh-sach-hoc-vien'
      preLoaderRoute: typeof AuthenticatedHocVienDanhSachHocVienLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/luong-gia/ket-qua': {
      id: '/_authenticated/luong-gia/ket-qua'
      path: '/luong-gia/ket-qua'
      fullPath: '/luong-gia/ket-qua'
      preLoaderRoute: typeof AuthenticatedLuongGiaKetQuaLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/luong-gia/quan-ly-form': {
      id: '/_authenticated/luong-gia/quan-ly-form'
      path: '/luong-gia/quan-ly-form'
      fullPath: '/luong-gia/quan-ly-form'
      preLoaderRoute: typeof AuthenticatedLuongGiaQuanLyFormLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBanToChucLazyRoute: typeof AuthenticatedBanToChucLazyRoute
  AuthenticatedCongViecChungLazyRoute: typeof AuthenticatedCongViecChungLazyRoute
  AuthenticatedGiangVienLazyRoute: typeof AuthenticatedGiangVienLazyRoute
  AuthenticatedMuaLazyRoute: typeof AuthenticatedMuaLazyRoute
  AuthenticatedNhatKyChinhSuaLazyRoute: typeof AuthenticatedNhatKyChinhSuaLazyRoute
  AuthenticatedQuanLyLoiTacVuLazyRoute: typeof AuthenticatedQuanLyLoiTacVuLazyRoute
  AuthenticatedTaiKhoanLazyRoute: typeof AuthenticatedTaiKhoanLazyRoute
  AuthenticatedTaiLieuLazyRoute: typeof AuthenticatedTaiLieuLazyRoute
  AuthenticatedIndexLazyRoute: typeof AuthenticatedIndexLazyRoute
  AuthenticatedChuDeDanhSachChuDeLazyRoute: typeof AuthenticatedChuDeDanhSachChuDeLazyRoute
  AuthenticatedChuDeGuiEmailLazyRoute: typeof AuthenticatedChuDeGuiEmailLazyRoute
  AuthenticatedChuDeNghiPhepLazyRoute: typeof AuthenticatedChuDeNghiPhepLazyRoute
  AuthenticatedDangKyMonKetQuaDangKyLazyRoute: typeof AuthenticatedDangKyMonKetQuaDangKyLazyRoute
  AuthenticatedDangKyMonQuanLyFormLazyRoute: typeof AuthenticatedDangKyMonQuanLyFormLazyRoute
  AuthenticatedHocVienDanhSachHocVienLazyRoute: typeof AuthenticatedHocVienDanhSachHocVienLazyRoute
  AuthenticatedLuongGiaKetQuaLazyRoute: typeof AuthenticatedLuongGiaKetQuaLazyRoute
  AuthenticatedLuongGiaQuanLyFormLazyRoute: typeof AuthenticatedLuongGiaQuanLyFormLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBanToChucLazyRoute: AuthenticatedBanToChucLazyRoute,
  AuthenticatedCongViecChungLazyRoute: AuthenticatedCongViecChungLazyRoute,
  AuthenticatedGiangVienLazyRoute: AuthenticatedGiangVienLazyRoute,
  AuthenticatedMuaLazyRoute: AuthenticatedMuaLazyRoute,
  AuthenticatedNhatKyChinhSuaLazyRoute: AuthenticatedNhatKyChinhSuaLazyRoute,
  AuthenticatedQuanLyLoiTacVuLazyRoute: AuthenticatedQuanLyLoiTacVuLazyRoute,
  AuthenticatedTaiKhoanLazyRoute: AuthenticatedTaiKhoanLazyRoute,
  AuthenticatedTaiLieuLazyRoute: AuthenticatedTaiLieuLazyRoute,
  AuthenticatedIndexLazyRoute: AuthenticatedIndexLazyRoute,
  AuthenticatedChuDeDanhSachChuDeLazyRoute:
    AuthenticatedChuDeDanhSachChuDeLazyRoute,
  AuthenticatedChuDeGuiEmailLazyRoute: AuthenticatedChuDeGuiEmailLazyRoute,
  AuthenticatedChuDeNghiPhepLazyRoute: AuthenticatedChuDeNghiPhepLazyRoute,
  AuthenticatedDangKyMonKetQuaDangKyLazyRoute:
    AuthenticatedDangKyMonKetQuaDangKyLazyRoute,
  AuthenticatedDangKyMonQuanLyFormLazyRoute:
    AuthenticatedDangKyMonQuanLyFormLazyRoute,
  AuthenticatedHocVienDanhSachHocVienLazyRoute:
    AuthenticatedHocVienDanhSachHocVienLazyRoute,
  AuthenticatedLuongGiaKetQuaLazyRoute: AuthenticatedLuongGiaKetQuaLazyRoute,
  AuthenticatedLuongGiaQuanLyFormLazyRoute:
    AuthenticatedLuongGiaQuanLyFormLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in': typeof authSignInLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/ban-to-chuc': typeof AuthenticatedBanToChucLazyRoute
  '/cong-viec-chung': typeof AuthenticatedCongViecChungLazyRoute
  '/giang-vien': typeof AuthenticatedGiangVienLazyRoute
  '/mua': typeof AuthenticatedMuaLazyRoute
  '/nhat-ky-chinh-sua': typeof AuthenticatedNhatKyChinhSuaLazyRoute
  '/quan-ly-loi-tac-vu': typeof AuthenticatedQuanLyLoiTacVuLazyRoute
  '/tai-khoan': typeof AuthenticatedTaiKhoanLazyRoute
  '/tai-lieu': typeof AuthenticatedTaiLieuLazyRoute
  '/': typeof AuthenticatedIndexLazyRoute
  '/chu-de/danh-sach-chu-de': typeof AuthenticatedChuDeDanhSachChuDeLazyRoute
  '/chu-de/gui-email': typeof AuthenticatedChuDeGuiEmailLazyRoute
  '/chu-de/nghi-phep': typeof AuthenticatedChuDeNghiPhepLazyRoute
  '/dang-ky-mon/ket-qua-dang-ky': typeof AuthenticatedDangKyMonKetQuaDangKyLazyRoute
  '/dang-ky-mon/quan-ly-form': typeof AuthenticatedDangKyMonQuanLyFormLazyRoute
  '/hoc-vien/danh-sach-hoc-vien': typeof AuthenticatedHocVienDanhSachHocVienLazyRoute
  '/luong-gia/ket-qua': typeof AuthenticatedLuongGiaKetQuaLazyRoute
  '/luong-gia/quan-ly-form': typeof AuthenticatedLuongGiaQuanLyFormLazyRoute
}

export interface FileRoutesByTo {
  '/500': typeof errors500LazyRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in': typeof authSignInLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/ban-to-chuc': typeof AuthenticatedBanToChucLazyRoute
  '/cong-viec-chung': typeof AuthenticatedCongViecChungLazyRoute
  '/giang-vien': typeof AuthenticatedGiangVienLazyRoute
  '/mua': typeof AuthenticatedMuaLazyRoute
  '/nhat-ky-chinh-sua': typeof AuthenticatedNhatKyChinhSuaLazyRoute
  '/quan-ly-loi-tac-vu': typeof AuthenticatedQuanLyLoiTacVuLazyRoute
  '/tai-khoan': typeof AuthenticatedTaiKhoanLazyRoute
  '/tai-lieu': typeof AuthenticatedTaiLieuLazyRoute
  '/': typeof AuthenticatedIndexLazyRoute
  '/chu-de/danh-sach-chu-de': typeof AuthenticatedChuDeDanhSachChuDeLazyRoute
  '/chu-de/gui-email': typeof AuthenticatedChuDeGuiEmailLazyRoute
  '/chu-de/nghi-phep': typeof AuthenticatedChuDeNghiPhepLazyRoute
  '/dang-ky-mon/ket-qua-dang-ky': typeof AuthenticatedDangKyMonKetQuaDangKyLazyRoute
  '/dang-ky-mon/quan-ly-form': typeof AuthenticatedDangKyMonQuanLyFormLazyRoute
  '/hoc-vien/danh-sach-hoc-vien': typeof AuthenticatedHocVienDanhSachHocVienLazyRoute
  '/luong-gia/ket-qua': typeof AuthenticatedLuongGiaKetQuaLazyRoute
  '/luong-gia/quan-ly-form': typeof AuthenticatedLuongGiaQuanLyFormLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in': typeof authSignInLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/ban-to-chuc': typeof AuthenticatedBanToChucLazyRoute
  '/_authenticated/cong-viec-chung': typeof AuthenticatedCongViecChungLazyRoute
  '/_authenticated/giang-vien': typeof AuthenticatedGiangVienLazyRoute
  '/_authenticated/mua': typeof AuthenticatedMuaLazyRoute
  '/_authenticated/nhat-ky-chinh-sua': typeof AuthenticatedNhatKyChinhSuaLazyRoute
  '/_authenticated/quan-ly-loi-tac-vu': typeof AuthenticatedQuanLyLoiTacVuLazyRoute
  '/_authenticated/tai-khoan': typeof AuthenticatedTaiKhoanLazyRoute
  '/_authenticated/tai-lieu': typeof AuthenticatedTaiLieuLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexLazyRoute
  '/_authenticated/chu-de/danh-sach-chu-de': typeof AuthenticatedChuDeDanhSachChuDeLazyRoute
  '/_authenticated/chu-de/gui-email': typeof AuthenticatedChuDeGuiEmailLazyRoute
  '/_authenticated/chu-de/nghi-phep': typeof AuthenticatedChuDeNghiPhepLazyRoute
  '/_authenticated/dang-ky-mon/ket-qua-dang-ky': typeof AuthenticatedDangKyMonKetQuaDangKyLazyRoute
  '/_authenticated/dang-ky-mon/quan-ly-form': typeof AuthenticatedDangKyMonQuanLyFormLazyRoute
  '/_authenticated/hoc-vien/danh-sach-hoc-vien': typeof AuthenticatedHocVienDanhSachHocVienLazyRoute
  '/_authenticated/luong-gia/ket-qua': typeof AuthenticatedLuongGiaKetQuaLazyRoute
  '/_authenticated/luong-gia/quan-ly-form': typeof AuthenticatedLuongGiaQuanLyFormLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/500'
    | '/forgot-password'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/ban-to-chuc'
    | '/cong-viec-chung'
    | '/giang-vien'
    | '/mua'
    | '/nhat-ky-chinh-sua'
    | '/quan-ly-loi-tac-vu'
    | '/tai-khoan'
    | '/tai-lieu'
    | '/'
    | '/chu-de/danh-sach-chu-de'
    | '/chu-de/gui-email'
    | '/chu-de/nghi-phep'
    | '/dang-ky-mon/ket-qua-dang-ky'
    | '/dang-ky-mon/quan-ly-form'
    | '/hoc-vien/danh-sach-hoc-vien'
    | '/luong-gia/ket-qua'
    | '/luong-gia/quan-ly-form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/500'
    | '/forgot-password'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/ban-to-chuc'
    | '/cong-viec-chung'
    | '/giang-vien'
    | '/mua'
    | '/nhat-ky-chinh-sua'
    | '/quan-ly-loi-tac-vu'
    | '/tai-khoan'
    | '/tai-lieu'
    | '/'
    | '/chu-de/danh-sach-chu-de'
    | '/chu-de/gui-email'
    | '/chu-de/nghi-phep'
    | '/dang-ky-mon/ket-qua-dang-ky'
    | '/dang-ky-mon/quan-ly-form'
    | '/hoc-vien/danh-sach-hoc-vien'
    | '/luong-gia/ket-qua'
    | '/luong-gia/quan-ly-form'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/500'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/ban-to-chuc'
    | '/_authenticated/cong-viec-chung'
    | '/_authenticated/giang-vien'
    | '/_authenticated/mua'
    | '/_authenticated/nhat-ky-chinh-sua'
    | '/_authenticated/quan-ly-loi-tac-vu'
    | '/_authenticated/tai-khoan'
    | '/_authenticated/tai-lieu'
    | '/_authenticated/'
    | '/_authenticated/chu-de/danh-sach-chu-de'
    | '/_authenticated/chu-de/gui-email'
    | '/_authenticated/chu-de/nghi-phep'
    | '/_authenticated/dang-ky-mon/ket-qua-dang-ky'
    | '/_authenticated/dang-ky-mon/quan-ly-form'
    | '/_authenticated/hoc-vien/danh-sach-hoc-vien'
    | '/_authenticated/luong-gia/ket-qua'
    | '/_authenticated/luong-gia/quan-ly-form'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignInLazyRoute: typeof authSignInLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  auth500Route: auth500Route,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignInLazyRoute: authSignInLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/500",
        "/(auth)/forgot-password",
        "/(auth)/sign-in",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/ban-to-chuc",
        "/_authenticated/cong-viec-chung",
        "/_authenticated/giang-vien",
        "/_authenticated/mua",
        "/_authenticated/nhat-ky-chinh-sua",
        "/_authenticated/quan-ly-loi-tac-vu",
        "/_authenticated/tai-khoan",
        "/_authenticated/tai-lieu",
        "/_authenticated/",
        "/_authenticated/chu-de/danh-sach-chu-de",
        "/_authenticated/chu-de/gui-email",
        "/_authenticated/chu-de/nghi-phep",
        "/_authenticated/dang-ky-mon/ket-qua-dang-ky",
        "/_authenticated/dang-ky-mon/quan-ly-form",
        "/_authenticated/hoc-vien/danh-sach-hoc-vien",
        "/_authenticated/luong-gia/ket-qua",
        "/_authenticated/luong-gia/quan-ly-form"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/ban-to-chuc": {
      "filePath": "_authenticated/ban-to-chuc.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/cong-viec-chung": {
      "filePath": "_authenticated/cong-viec-chung.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/giang-vien": {
      "filePath": "_authenticated/giang-vien.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/mua": {
      "filePath": "_authenticated/mua.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/nhat-ky-chinh-sua": {
      "filePath": "_authenticated/nhat-ky-chinh-sua.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/quan-ly-loi-tac-vu": {
      "filePath": "_authenticated/quan-ly-loi-tac-vu.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tai-khoan": {
      "filePath": "_authenticated/tai-khoan.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tai-lieu": {
      "filePath": "_authenticated/tai-lieu.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chu-de/danh-sach-chu-de": {
      "filePath": "_authenticated/chu-de/danh-sach-chu-de.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chu-de/gui-email": {
      "filePath": "_authenticated/chu-de/gui-email.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chu-de/nghi-phep": {
      "filePath": "_authenticated/chu-de/nghi-phep.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dang-ky-mon/ket-qua-dang-ky": {
      "filePath": "_authenticated/dang-ky-mon/ket-qua-dang-ky.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dang-ky-mon/quan-ly-form": {
      "filePath": "_authenticated/dang-ky-mon/quan-ly-form.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/hoc-vien/danh-sach-hoc-vien": {
      "filePath": "_authenticated/hoc-vien/danh-sach-hoc-vien.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/luong-gia/ket-qua": {
      "filePath": "_authenticated/luong-gia/ket-qua.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/luong-gia/quan-ly-form": {
      "filePath": "_authenticated/luong-gia/quan-ly-form.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
